project:
  title: "PowerShell TDD 起步走"
  render: 
    - slides/index.qmd

# picture url prefix
part1_img_prefix: "./01_IDE_Setup/"
part2_img_prefix: "./02_Pester_Intro/"
part3_img_prefix: "./03_Binary_Cmdlet/"
part4_img_prefix: "./03_AspNetCore_Host/"