## Pester - PowerShell Test Framework

* [Pester](http://pester.dev) 是一個 PowerShell 的全家桶測試框架，可以用來撰寫測試案例、執行測試案例、產生測試報告。
* 提供 [Assertion Syntax](http://pester.dev/docs/assertions/) / [Mock](http://pester.dev/docs/usage/mocking) / [Test Runner](http://pester.dev/docs/commands/Invoke-Pester) / [Code Coverage](http://pester.dev/docs/usage/code-coverage) 等進行測試驅動開發時需要的功能。
* 提供測試用虛擬磁碟 [`TestDrive:`](http://pester.dev/docs/usage/testdrive) /<br/>虛擬 Windows Registry [`TestRegistry:`](http://pester.dev/docs/usage/testregistry) 的執行環境隔離功能，方便進行測試程式碼撰寫。
* 跟 VSCode PowerShell Extension 整合，可在 [VSCode 的 Code Lens中直接執行/除錯特定的單一 Pester 測試案例](http://pester.dev/docs/usage/vscode)。
* PowerShell 官方也使用此測試框架來寫測試案例。<br/><https://github.com/PowerShell/PowerShell/blob/master/docs/testing-guidelines/WritingPesterTests.md>

## Pester 撰寫測試案例程式碼重點 {.small .scrollable}

* 以 `Describe` 來描述測試案例的主題，以 `Context` 來描述測試案例的子主題，以 `It` 來描述測試案例的斷言(Test Case)。
* 雖然 Pester 自己預設行為是去搜尋執行目錄下以 `.Tests.ps1` 檔案名結尾的 PowerShell Script 檔案作為測試案例程式碼執行，但是得自行處理待測試 PowerShell Script 檔案( .ps1/.psm1 )的模組載入問題。
* 透過 [`Mock`](http://pester.dev/docs/usage/mocking) 來模擬外部依賴的PowerShell函式呼叫/原生應用程式執行，以達到隔離測試的目的：
    * `Mock` 會在測試案例執行前將原本的函式/程式替換成 Mock 所定義的行為，測試案例執行完畢後再還原。
      * Pester 的 Mock 功能在 PowerShell v7+ 支援較好，建議測試案例的 script 程式碼儘量用 PowerShell v7+ 的環境來執行。
      * Pester 底層使用 [PowerShell Alias 功能](http://learn.microsoft.com/powershell/scripting/learn/shell/using-aliases)實現 Mock 命令實作。
      * 當宣告 Mock 時，**要蓋掉的 PowerShell Cmdlet/函式命令 必須已存在於待測試程式碼的 Module Scope 內，否則 Pester 會無法蓋掉，轉而拋出執行錯誤。**
      * 宣告的 Mock 在使用命令的程式碼所在的 Module [作用域(Module Scope)](http://learn.microsoft.com/powershell/module/microsoft.powershell.core/about/about_scopes) 內有效，而非全域有效。
    * `Mock` 會記錄 Mock 物件的呼叫次數、參數、回傳值等資訊，方便撰寫測試案例時檢查。
    * `Mock` 無法蓋掉使用 binary cmdlet 載入的 C# Cmdlet 函式，因為同名模組中的函式呼叫優先順序 ***C# >>> PowerShell***。
* 透過 `TestDrive:` 來建立虛擬磁碟空間，以達到隔離測試的目的。
* 透過 `TestRegistry:` 來建立虛擬 Windows Registry 空間，以達到隔離測試的目的。
* 必要時可建立 Customer Pester Assertion 以便簡化驗證測試結果的程式碼區塊的撰寫。

## Pester 為既有程式撰寫測試案例程式碼範例

### ***Demo***

[範例程式碼 GitHub](http://github.com/windperson/DemoPester)

* 系統性的制式 Data-Driven 測試案例架構來驗證各模組函式的輸入參數名稱、型別、回傳值。
* 由於 PowerShell 對於 .ps1 & .psm1 模組載入機制的不同，會造成某些待測模組的程式碼寫法，很不容易撰寫測試程式碼。
  * `InModuleScope` 以便在待測模組載入時的環境變數設定自定義邏輯(塞入固定參數/Mock/Assertion程式碼)。
  * 藉由先宣告一些 Dummy function 來『先佔位』以便順利進行宣告 MOck 語法，然後再載入模組以便進行測試。
* Pester Custom Assertion 的撰寫及註冊使用。

## 系統性制式 Data-Driven 測試案例架構驗證<br/>模組函式 輸入參數名稱/型別/回傳型別{.smaller .scrollable}

雖然 PowerShell 是 Strongly Typed Language，但是在專案寫大寫複雜時，仍然需要一些驗證機制來確定層層呼叫函式的輸入參數名稱、型別、回傳值型別是否正確。<br/>
（ 避免跑script時被一堆 **Command/Parameter Not Found** 搞死）

先說結論： 

> 藉由自行定義儲存 key-value 物件的 PowerShell 陣列，<br/>描述函式的名稱、輸入參數、回傳值，透過 Pester 的測試案例來驗證載入之模組有這些函式。

```powershell{.ps1 filename="Demo1to1MappingTestModule\Production_test\ProductFeatures\MathFeatureModule\MathFeature.Tests.ps1" code-line-numbers="4-42" }
Describe "Math function API declaration" -Tag "MathFeature", "FunctionDeclaration" {
    BeforeDiscovery {
        #region API definitions
        $ApiDefinition = @(
            @{
                Name        = 'Invoke-Add'
                CommandType = [System.Management.Automation.CommandTypes]::Function;
                Inputs      = @{
                    a = [int]
                    b = [int]
                }
                Outputs     = @([int])
            }
            @{
                Name        = 'Invoke-Sub'
                CommandType = [System.Management.Automation.CommandTypes]::Function;
                Inputs      = @{
                    a = [int]
                    b = [int]
                }
                Outputs     = @([int])
            }
            @{
                Name        = 'Invoke-Mul'
                CommandType = [System.Management.Automation.CommandTypes]::Function;
                Inputs      = @{
                    a = [int]
                    b = [int]
                }
                Outputs     = @([int])
            }
            @{
                Name        = 'Invoke-Div'
                CommandType = [System.Management.Automation.CommandTypes]::Function;
                Inputs      = @{
                    a = [int]
                    b = [int]
                }
                Outputs     = @([int])
            }
        )
        #endregion
    }
    BeforeAll {
        . (Resolve-Path $UtiltiyModulePath\VerifyPsDefApi.ps1)
    }

    It "Should have API `'<Name>`' defined in ApiDefinition" -ForEach $ApiDefinition {
        VerifyApiDefinition -Name $Name -CommandType $CommandType
    }
}
```

原理是使用 [`Get-Command`](http://learn.microsoft.com/powershell/module/microsoft.powershell.core/get-command) Cmdlet 來取得函式的 [CommandInfo](http://learn.microsoft.com/dotnet/api/system.management.automation.commandinfo) 物件，再透過 Pester 的各項屬性之測試案例來驗證各項資訊：

*Step 1*: 驗證此函式是否存在於目前可使用的PowerShell模組之中。
```powershell {.ps1 filename="Demo1to1MappingTestModule\Production_test\VerifyPsDefApi.ps1" code-line-numbers="false" }
function VerifyApiType() {
    param(
        [string] $Name,
        [System.Management.Automation.CommandTypes] $CommandType = [System.Management.Automation.CommandTypes]::Function
    )

    Process {
        $targetExists = Get-Command -Name $Name -CommandType $CommandType -ErrorAction SilentlyContinue                   # <1>
        $targetExists | Should -Not -BeNullOrEmpty                                                                        # <1> 
        return $targetExists
    }
}
```
1. 使用 `Get-Command` Cmdlet 來取得函式的參數資訊 CommandInfo 物件，然後透過 Pester 的測試案例確認物件存在，否則 test failed。

*Step 2*: 驗證此函式的輸入參數名稱、型別是否正確。

```powershell {.ps1 filename="Demo1to1MappingTestModule\Production_test\VerifyPsDefApi.ps1" code-line-numbers="18,23,27,28" }
function VerifyApiInputParameters {
    param(
        [ValidateNotNull()]
        [System.Management.Automation.CommandInfo]
        $commandInfo,
        [System.Collections.Hashtable]$designedParameters
    )
    # Note: since PowerShell's built-in Hashtable is case insensitive, we can't use it to exactly check function parameters
    $parameterTable = New-Object 'System.Collections.Hashtable'
    foreach ($key in $designedParameters.Keys) {
        $parameterTable.Add($key, $designedParameters[$key])
    }

    $cmdletBuiltInParameters =
    @('Verbose', 'Debug', 'ErrorAction', 'ErrorVariable', 'InformationAction', 'InformationVariable', 'WarningAction', 'WarningVariable', 'OutBuffer', 'OutVariable', 'PipelineVariable', 'ProgressAction',
        'WhatIf', 'Confirm')

    foreach ($parameter in $commandInfo.Parameters.Values.GetEnumerator()) {
        $parameterName = $parameter.Name
        if ( $commandInfo.CmdletBinding -and $cmdletBuiltInParameters -contains $parameterName) {
            continue
        }
        $parameterTable.ContainsKey($parameterName) | Should -Be $true -Because "Parameter '$parameterName' should be exist"
        $expectedType = $parameterTable[$parameterName]
        # We compare type by its full name string, not rely on Pester's -BeOfType assertion
        # see https://github.com/pester/Pester/issues/1315#issuecomment-756700291
        $parameterTypeName = $parameter.ParameterType.FullName
        $parameterTypeName | Should -Be $expectedType.ToString() -Because "Parameter '`$$parameterName' should be of type '$expectedType'"
    }
}
```

## Pester Mock 功能在 InModuleScope 的***敏捷***使用 {.smaller .scrollable}

在撰寫測試案例程式碼時，有時候會遇到待測試的 PowerShell Script 檔案中的函式呼叫，會依賴於其他函式的回傳值，這時候就需要使用 Pester 的 Mock 功能來模擬外部函式的回傳值。
而定義在模組內但沒有 export 的函式，外界摸不到，這時候就需要使用 `InModuleScope` 區塊功能來正確定義要操作的內部函式 Mock。

例如以下待測 PowerShell Script 檔案：

```powershell {.ps1 filename="DemoScope\DemoUseAndRemoveMock\MyScript.psm1" code-line-numbers="1-6,14" }
function Get-CurrentTime {
    param()
    $output = (Get-Date).ToString()
    Write-Information -MessageData "In Real Get-CurrentTime() function, `$output=$output" -InformationAction Continue
    return $output
}

function MyDateTime {
    param()
    $time = Get-CurrentTime
    return "The current time is $time"
}

Export-ModuleMember MyDateTime
```

::: {.callout-tip}
由於 `Get-CurrentTime` 函式沒有 export，所以外部無法直接對其 Mock 以避免測試結果會每次執行時都不同<br/>(`Get-CurrentTime` 內部有呼叫 [`Get-Date`](https://learn.microsoft.com/powershell/module/microsoft.powershell.utility/get-date) 取得實際時間），<br/>需使用 [`InModuleScope`](https://pester.dev/docs/commands/InModuleScope) 區塊在正確的PowerShell module 作用域內部定義 Mock。
:::

測試程式碼：

```powershell {.ps1 filename="DemoScope\DemoUseAndRemoveMock\MyScript.Tests.ps1" code-line-numbers="true" }
Describe "MyFunction" {
    BeforeAll {
        Import-Module "$PSScriptRoot/MyScript.psm1" -Verbose -Force
    }
    It "should return the mocked time" {
        InModuleScope MyScript {                                            # <1>
            Mock -CommandName Get-CurrentTime -MockWith {                   # <1>
                $output = "2024-11-14 08:00:00"                             # <1>
                Write-Information -MessageData `                            # <1>
                    "In Mocked Get-CurrentTime(), output=$output" `         # <1>
                    -InformationAction Continue                             # <1>
                return $output                                              # <1>                                   
            }                                                               # <1>

            $result = MyDateTime                                            # <2>
            $result | Should -Be "The current time is 2024-11-14 08:00:00"  # <2>

            # Remove mocked Get-CurrentTime Function
            Remove-Alias Get-CurrentTime                                    # <3> 
        }

        # Call the function again and check the result without the mock
        $result = MyDateTime                                                # <4> 
        $result | Should -Not -Be "The current time is 2024-11-14 08:00:00" # <4>
    }
}
```
1. 使用 `InModuleScope` 區塊來定義 Mock 的函式，這樣就可以在正確的 PowerShell module 作用域內部定義 Mock。
2. 在 `InModuleScope` 區塊內部執行待測試的函式，並驗證其回傳值是否為前一步驟 Mock 的回傳值。
3. 移除 Mock 的方法就是呼叫 [Remove-Alias](http://learn.microsoft.com/powershell/module/microsoft.powershell.utility/remove-alias) Cmdlet。
4. 移除 Mock 後再次執行待測試的函式，並驗證其回傳值是否正確。

所以在更為複雜的實際PowerShell Script專案架構中，可以使用此技巧撰寫測試案例程式碼提高 code coverage rate。

::: {.callout-note}
更複雜的如：<br>***載入 .ps1 script檔時會立刻執行的函式如何 Mock ？***<br/>參閱此範例專案的<br/>[`Demo1to1MappingTestModule/Production_test/ProductFeatures/StringFeatureModule/FormatDateTime.Tests.ps1`](https://github.com/windperson/DemoPester/blob/main/Demo1to1MappingTestModule/Production_test/ProductFeatures/StringFeatureModule/FormatDateTime.Tests.ps1#L28)</br>測試案例程式碼
:::

## Pester Custom Assertion {.smaller .scrollable}

Pester 沒有提供浮點數值精確度比較的 Assertion Cmdlet, 所以就自己動手寫一個：

```powershell{.ps1 filename="Demo1to1MappingTestModule\Production_test\ProductFeatures\MathFeatureModule\MathFeature.Tests.ps1" code-line-numbers="false" }
function Should-BeEqualWithPrecision(                                                                          # <1>
  [double] $ActualValue, [double] $ExpectValue,                                                                # <2>
  [uint] $Precision,                                                                                           # <2>
  [switch] $Negate,                                                                                            # <2>
  [string] $Because                                                                                            # <2>
) {
    $pass = [math]::Round($ActualValue, $Precision) -eq [math]::Round($ExpectValue, $Precision)                # <3>
    if ($Negate) {                                                                                             # <4>
        $pass = -not $pass                                                                                     # <4>
    }                                                                                                          # <4>

    if (-not $pass) {                                                                                          # <5>
        if ($Negate) {                                                                                         # <5> 
            $failureMessage =                                                                                  # <5>
              "Expected '$ActualValue' to not be equal to $ExpectValue$(if($Because) { " because $Because"})." # <5>
        }                                                                                                      # <5>
        else {                                                                                                 # <5> 
            $failureMessage =                                                                                  # <5>
              "Expected '$ActualValue' to be equal to $ExpectValue$(if($Because) { " because $Because"})."     # <5>
        }                                                                                                      # <5>
    }                                                                                                          # <5>

    return [pscustomobject]@{                                                                                  # <6>
        Succeeded      = $pass                                                                                 # <6>
        FailureMessage = $failureMessage                                                                       # <6>
    }                                                                                                          # <6>
}
```
1. Pester Custom Assertion 就是一個自己寫的 [PowerShell Simple Function](http://learn.microsoft.com/powershell/scripting/learn/ps101/09-functions#a-simple-function)，`Verb-Noun` 的命名風格是 **Verb** 為 `Should` 不可改動，**Noun** `BeEqualWithPrecision` 為我們自己定義的名稱。
2. 輸入和輸出的格式區符合 Pester 的規範：`$ActualValue` 是實際值，`$Negate` 是設定是否反轉布林邏輯，`$Because` 是 Assertion 失敗時的訊息，這三個輸入參數名稱一定要正確；而`$ExpectValue` 預期值和設定浮點數值精確度的 `$Precision` 是我們自己定義的額外輸入參數，可於撰寫測試程式碼的 Assertion statements 時多指定在程式碼中。
3. 這個 Custom Assertion 的實作是透過將兩個浮點數值四捨五入到指定精確度後再比較是否相等，以達到比較浮點數值的精確度比較。
4. 假如有指定 `$Negate` 參數，則反轉判斷結果的布林值。
5. 為不同的 Assertion 結果設定不同的錯誤訊息。
6. 最後回傳一個 [PSCustomObject](http://learn.microsoft.com/powershell/scripting/learn/deep-dives/everything-about-pscustomobject) 物件，其中包含了 Assertion 的結果布林值(`Succeeded`)和錯誤訊息(`FailureMessage`)。

然後在測試案例程式碼中先呼叫 [`Add-ShouldOperator`](https://pester.dev/docs/commands/Add-ShouldOperator)註冊:
```powershell {.ps1 filename="Demo1to1MappingTestModule/Production_test/ProductFeatures/MathFeatureModule/MathFeature.Tests.ps1" }
Add-ShouldOperator -Name BeEqualWithPrecision -Test ${Function:Should-BeEqualWithPrecision}
```
就可以在撰寫測試案例程式碼時使用 `Should -BeEqualWithPrecision` 這個 Custom Assertion 了：
```powershell {.ps1 filename="Demo1to1MappingTestModule/Production_test/ProductFeatures/MathFeatureModule/MathFeature.Tests.ps1" }
$actual | Should -BeEqualWithPrecision -ExpectValue $expect -Precision 2
```
